name: home_decor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  intl: ^0.20.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: '#F4B5A4'
  image: assets/images/splashimage.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/



